new abstract proposal to close #133
anima-wg/constrained-voucher pull request #198
Opened 2021-11-26 16:47 UTC by EskoDijk

close #133

2021-11-30 11:32 UTC, petervanderstok requested changes
Replace:
"And where BRSKI uses HTTPS transactions, Constrained BRSKI uses CoAPS instead.
Also, the Enrollment over Secure Transport (EST) protocol as used in BRSKI is replaced here by EST-over-CoAPS. "
with
"The Enrollment over Secure Transport (EST) protocol, used in BRSKI, is replaced with EST-over-CoAPS; additionally https used by BRSKI is replaced with CoAPS".

2021-12-02 14:16 UTC, mcr commented on constrained-voucher.mkd
> +This document extends and updates BRSKI {{RFC8995}}, the voucher format {{RFC8366}} and EST-over-CoAPs {{I-D.ietf-ace-coap-est}}.
I think we should cut after line 118.
It gets too long and detailed, and there aren't supposed to be references in the abstract.

2021-12-02 15:07 UTC, mcr approved these changes

2021-12-02 15:07 UTC, mcr commented on constrained-voucher.mkd
> +This document extends and updates BRSKI {{RFC8995}}, the voucher format {{RFC8366}} and EST-over-CoAPs {{I-D.ietf-ace-coap-est}}.
```suggestion

```

2021-12-02 15:08 UTC, merged