BRSKI well-known URI registry registrations added
anima-wg/constrained-voucher pull request #216
Opened 2022-02-03 16:33 UTC by EskoDijk

2022-02-10 15:58 UTC, EskoDijk commented
@mcr Updated this PR according to our discussion. I also wanted to improve the names of the registered items as we go, because that was quite bad.

2022-02-10 18:25 UTC, mcr requested changes

2022-02-10 18:25 UTC, mcr commented on constrained-voucher.mkd
> +by adding a field "Short URI". The contents of this field MUST be specified for any newly registered URI as follows:
```suggestion
by adding a new column "Short URI". The contents of this field MUST be specified for any newly registered URI as follows:
```

2022-02-11 13:45 UTC, mcr approved these changes

2022-02-11 14:18 UTC, merged