added IANA registries for BRSKI objective values
anima-wg/constrained-voucher pull request #272
Opened 2023-07-26 00:39 UTC by mcr

This adds IANA Considerations for the two BRSKI grasp messages' objective-values.

2023-08-08 15:40 UTC, mcr commented
1. Headings for tables are wrong.
2. missing IANA Considerations for extensions

2023-09-01 10:01 UTC, EskoDijk requested changes
added some comments/questions!

2023-09-01 10:01 UTC, EskoDijk commented on constrained-voucher.mkd
> +| string           | defined in |
see "string" comment in above table - it may be any CBOR type?

2024-01-10 08:50 UTC, EskoDijk commented
Closing this PR, GRASP related definitions will be moved out of the draft as per -23.

2024-01-10 08:50 UTC, closed without merging