rewrite intro and abstract
anima-wg/constrained-voucher pull request #68
Opened 2021-01-07 04:00 UTC by mcr

2021-01-07 09:37 UTC, EskoDijk requested changes
Overall the new text isn't clear enough yet. In the current proposal we see a mix of paragraphs that have a different viewpoint on what this document is:
1) "old" viewpoint - this document just describes a constrained version of the voucher and nothing more. E.g. the title also reflects this. Bootstrap protocol use of HTTP or CoAP should be irrelevant to this. We don't define a complete constrained BRSKI solution but only a Voucher format that other docs can use.
2) "new" viewpoint - we define constrained BRSKI including all it needs like voucher format, protocol use of CoAP, CoAP resources, Registrar-to-MASA communication, etc.  A much wider scope!

Before I can propose sensible review comments we must first decide what our aim is with this document.  Should we make a split between constrained voucher format and "rest" of the bootstrap protocol, like BRSKI did? Or do we want to integrate everything into one draft?

2021-01-07 10:18 UTC, petervanderstok commented
Hi Esko,

Good point.
I like a constrained "pun" purpose document.
However, some assumptions on the protocol should be described.
I would prefer not to go into the options of how to use the voucher
contents and under which circumstances.
For me that is clearly another document.
The motivation why the different items are in the voucher or VR should
be discussed wen they exceed the brski document.

Peter
Esko Dijk schreef op 2021-01-07 10:37:

> @EskoDijk requested changes on this pull request. 
> 
> Overall the new text isn't clear enough yet. In the current proposal we see a mix of paragraphs that have a different viewpoint on what this document is: 
> 
> * "old" viewpoint - this document just describes a constrained version of the voucher and nothing more. E.g. the title also reflects this. Bootstrap protocol use of HTTP or CoAP should be irrelevant to this. We don't define a complete constrained BRSKI solution but only a Voucher format that other docs can use.
> * "new" viewpoint - we define constrained BRSKI including all it needs like voucher format, protocol use of CoAP, CoAP resources, Registrar-to-MASA communication, etc. A much wider scope!
> 
> Before I can propose sensible review comments we must first decide what our aim is with this document. Should we make a split between constrained voucher format and "rest" of the bootstrap protocol, like BRSKI did? Or do we want to integrate everything into one draft? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/anima-wg/constrained-voucher/pull/68#pullrequestreview-563338595
[2]
https://github.com/notifications/unsubscribe-auth/ADCZGQKLDSL6FASPGMYREW3SYV6G3ANCNFSM4VYNH6WQ

2021-01-11 09:11 UTC, EskoDijk approved these changes

2021-01-11 09:11 UTC, EskoDijk commented
Proposed further edits in my last commit, for review!

2021-01-14 12:23 UTC, mcr commented on constrained-voucher.mkd
> +or indirectly, by the pledge's manufacturer.  This artifact is known as a "voucher".
What is the "indirect" situation?

2021-01-14 12:32 UTC, mcr commented on constrained-voucher.mkd
> +or indirectly, by the pledge's manufacturer.  This artifact is known as a "voucher".
```suggestion
This document defines a protocol to securely assign a pledge to an
owner and to enroll it into the owner's network. 
The protocol uses an artifact that is signed by the pledge's manufacturer.  
This artifact is known as a "voucher".
```

2021-01-14 12:34 UTC, merged